# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://agitated-wilson-c9a216.netlify.com/"
languageCode = "en-AU"
title = "Airowin"

# Metadata
[params]
  author = "Your name"
  description = "Cool description"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/hero_bg.jpg"
  title = "Airowin"
  description = "Improving experiences by using meaningful engagement and collaboration."

